<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="TngTech.ArchUnitNET" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Whetstone.Domain\Whetstone.Domain.csproj" />
    <ProjectReference Include="..\..\src\Whetstone.Application\Whetstone.Application.csproj" />
    <ProjectReference Include="..\..\src\Whetstone.Infrastructure\Whetstone.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Whetstone.Web\Whetstone.Web.csproj" />
    <ProjectReference Include="..\..\src\Whetstone.Web.Client\Whetstone.Web.Client.csproj" />
    <ProjectReference Include="..\..\src\Whetstone.Worker\Whetstone.Worker.csproj" />
  </ItemGroup>

</Project>